import React,{useState,useEffect,useRef} from 'react';
import gsap from 'gsap';
import {ArrowUpRight,ArrowRight,Building2,Armchair,BriefcaseBusiness,ChartNoAxesCombined} from 'lucide-react';
import {Logo,SiteHeader,SiteFooter,EnquiryDialog,AboutArchitecture} from './App.jsx';
import './about.css';
export const aboutMeta={title:'About BHB Business Hub | Business Centre in Dubai',description:'Meet BHB Business Hub in Dubai: an integrated approach to business setup, office solutions, PRO coordination, and accounting and tax support enquiries.'};
const capabilities=[
 {icon:Building2,title:'Business Setup',enquiry:'Company formation',text:'Explore mainland and free zone formation options. Start with your business activity, then discuss the licensing route, documents and workspace needs that shape your next steps.'},
 {icon:Armchair,title:'Office Solutions',enquiry:'Flexible offices',text:'Explore private, serviced and virtual office options in Dubai. Discuss how you work, what your team needs and the type of business presence you want to establish.'},
 {icon:BriefcaseBusiness,title:'PRO Services',enquiry:'Business support',text:'Discuss support with business documentation and government-related processes. Bring your administrative requirements together, with next steps shaped around the relevant authority and the needs of your company.'},
 {icon:ChartNoAxesCombined,title:'Accounting & Tax Support',enquiry:'Accounting & VAT',text:'Discuss your accounting and tax-related needs, from record organisation to finding the right professional support. The scope of support is clarified before any engagement begins.'}
];
const reasons=[{title:'One connected hub',text:'Consider setup, workspace and ongoing support together, rather than as separate decisions.'},{title:'Less to coordinate',text:'Bring your requirements into one conversation, with a clearer view of what comes next.'},{title:'A considered starting point',text:'Begin with your business activity, priorities and practical needs.'},{title:'Space that fits',text:'Explore office options around your working style and business presence.'}];
export default function AboutPage(){
 const [menu,setMenu]=useState(false),[enquiry,setEnquiry]=useState(null),[sent,setSent]=useState(false);const page=useRef(null);const enquiryTrigger=useRef(null);
 const open=value=>{enquiryTrigger.current=document.activeElement;setSent(false);setEnquiry(value);setMenu(false)};
 useEffect(()=>{document.title=aboutMeta.title;const description=document.querySelector('meta[name="description"]');if(description)description.content=aboutMeta.description;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const context=gsap.context(()=>{if(!reduced)gsap.fromTo('.about-hero .about-enter',{opacity:0,y:18},{opacity:1,y:0,stagger:.12,duration:.9,ease:'power2.out',clearProps:'opacity,transform'})},page);return()=>context.revert()},[]);
 useEffect(()=>{if(!enquiry)return;const previous=enquiryTrigger.current;const modal=document.querySelector('.modal');const focusable=()=>[...modal.querySelectorAll('button,input,textarea,a[href]')];const key=e=>{if(e.key==='Escape'){setEnquiry(null);return}if(e.key==='Tab'){const items=focusable(),first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};const overflow=document.body.style.overflow;document.body.style.overflow='hidden';window.addEventListener('keydown',key);return()=>{document.body.style.overflow=overflow;window.removeEventListener('keydown',key);if(previous?.isConnected)previous.focus();else document.querySelector('.menu-toggle')?.focus()}},[enquiry]);
 return <div className="about-page" ref={page}><AboutArchitecture/><a className="about-skip-link" href="#about-content">Skip to content</a><main inert={enquiry?true:undefined}><SiteHeader menu={menu} setMenu={setMenu} open={open} about/><div id="about-content" tabIndex={-1}>
 <section className="about-hero" aria-labelledby="about-title"><div className="about-hero-copy"><p className="eyebrow about-enter"><i/> ABOUT BHB BUSINESS HUB</p><h1 id="about-title" className="about-enter">Your business.<br/><em>Our expertise.</em></h1><p className="about-lead about-enter">A business centre in Dubai, bringing your business needs together. From establishing your presence to finding your workspace, we start with what matters to you.</p><a className="about-hero-link about-enter" href="#who-we-are">Discover our approach <ArrowRight size={18}/></a><div className="about-address about-enter"><span/> DUBAI, UNITED ARAB EMIRATES</div></div><div className="about-brand-frame about-enter" aria-hidden="true"><span className="frame-label">A GATEWAY TO POSSIBILITY</span><Logo/><span className="frame-slogan">The Art of All Business Needs.</span><span className="frame-location">DUBAI, UAE</span></div><span className="about-hero-index">02 / ABOUT BHB</span></section>
 <div className="about-sections">
 <section className="about-who about-section" id="who-we-are" aria-labelledby="who-title"><div><p className="eyebrow">01 / WHO WE ARE</p><h2 id="who-title">A place for business.<br/><em>A partner in possibility.</em></h2></div><div className="about-who-copy"><p>BHB Business Hub brings workspace and business-related support into one setting. Based in Dubai, our focus is on helping you connect the practical needs of running a business.</p><p>We look at the whole picture: your setup plans, your office requirements and your day-to-day operations. A connected approach gives every conversation a clearer starting point.</p><div className="about-signature"><span className="signature-line"/> THE ART OF ALL BUSINESS NEEDS</div></div></section>
 <section className="about-capabilities about-section" aria-labelledby="capabilities-title"><div className="section-heading"><div><p className="eyebrow">02 / WHAT WE DO</p><h2 id="capabilities-title">Your needs.<br/><em>Connected.</em></h2></div><p>Four areas of support.<br/>One considered approach.</p></div><div className="service-grid">{capabilities.map(({icon:Icon,title,text,enquiry},i)=><button className="service-card about-service" key={title} onClick={()=>open(enquiry)}><div className="card-top"><Icon size={29} strokeWidth={1}/><span>0{i+1}</span></div><h3>{title}</h3><p>{text}</p><span className="card-link">Discuss your needs <ArrowUpRight size={18}/></span></button>)}</div></section>
 <section className="about-why about-section" aria-labelledby="why-title"><div className="about-why-intro"><p className="eyebrow">03 / WHY BHB</p><h2 id="why-title">Connected<br/><em>by design.</em></h2><p>Business decisions rarely stand alone.<br/>Your support shouldn’t either.</p></div><div className="about-reasons">{reasons.map(({title,text},i)=><article key={title}><span className="reason-number">0{i+1}</span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></section>
 <section className="about-approach about-section" aria-labelledby="approach-title"><p className="eyebrow">04 / OUR APPROACH</p><h2 id="approach-title">Listen first.<br/><em>Move with purpose.</em></h2><ol className="about-steps"><li><span>01</span><h3>Understand</h3><p>Start with your plans, priorities and the way you want to work.</p></li><li><span>02</span><h3>Connect</h3><p>Consider the setup, workspace and support options relevant to your business.</p></li><li><span>03</span><h3>Clarify</h3><p>Agree the scope of support and a practical next step before moving forward.</p></li></ol></section>
 <section className="about-cta" aria-labelledby="cta-title"><p className="eyebrow">YOUR NEXT CHAPTER</p><h2 id="cta-title">Let’s build your<br/><em>business together.</em></h2><p>Tell us what you have in mind.</p><button className="gold-button" onClick={()=>open('General enquiry')}>Contact Us <ArrowUpRight size={19}/></button></section>
 </div></div><SiteFooter/></main>{enquiry&&<EnquiryDialog enquiry={enquiry} sent={sent} onClose={()=>setEnquiry(null)} onSent={()=>setSent(true)}/>}</div>
}
