import React,{useState,useEffect,useRef} from 'react';
import {ArrowUpRight,ArrowRight,Plus,X} from 'lucide-react';
import {SiteHeader,SiteFooter,EnquiryDialog} from './App.jsx';
import './about.css';
import './showcase.css';
export const expertiseMeta={title:'Our Expertise & Team | BHB Business Hub Dubai',description:'Meet Ahmed Marey, Sales Manager, and Fasia, Admin & Sales Executive, at BHB Business Hub. Explore business setup, workspace and business support enquiries in Dubai.'};
export const spacesMeta={title:'Our Spaces | BHB Business Hub Dubai',description:'Explore photographs of BHB Business Hub’s reception, private offices, shared workspaces and meeting room in Dubai. Discuss your workspace needs with our team.'};
const team=[{id:'ahmed',name:'Ahmed Marey',role:'Sales Manager'},{id:'fasia',name:'Fasia',role:'Admin & Sales Executive'}];
const rooms=[{id:'reception',name:'A warm welcome',type:'Reception',alt:'BHB reception desk with the black and gold BHB logo, blue carpet, plants and wall-mounted TV'},{id:'private',name:'Room to focus',type:'Private office',alt:'Private office with a desk, executive chair and sofa beside full-height windows'},{id:'shared',name:'Work alongside your team',type:'Shared workspace',alt:'Shared office with white desks, dividers, black chairs and daylight from the window'},{id:'meeting',name:'Bring ideas together',type:'Meeting room',alt:'Meeting room with a long white table and black chairs inside glass partitions'},{id:'daylight',name:'A brighter working day',type:'Window office',alt:'Window office with white desks, black chairs and blue and grey carpet'}];
const support=[['Company formation','Business setup','Discuss mainland and free zone formation options around your business activity and plans.'],['Flexible offices','Office solutions','Find a working environment around your team, your routine and your business presence.'],['Business support','PRO & business support','Bring your documentation and administrative requirements into one conversation.'],['Accounting & VAT','Accounting & VAT','Discuss your accounting and tax support needs, with the scope clarified before engagement.']];
function Photo({id,alt,portrait=false,eager=false}){return <img src={`/photos/${id}-960.webp`} srcSet={`/photos/${id}-480.webp 480w, /photos/${id}-960.webp 960w, /photos/${id}-1440.webp 1440w`} sizes={portrait?'(max-width: 600px) 86vw, (max-width: 900px) 42vw, 400px':id==='reception'?'88vw':'(max-width: 600px) 86vw, 44vw'} width={portrait?960:1440} height={portrait?1200:id==='meeting'?960:1080} alt={alt} loading={eager?'eager':'lazy'} decoding="async"/>}
function useDialog(active,close,trigger){useEffect(()=>{if(!active)return;const modal=document.querySelector('[role="dialog"]'),before=trigger.current,overflow=document.body.style.overflow;document.body.style.overflow='hidden';const first=modal?.querySelector('button,input');first?.focus();const handler=e=>{if(e.key==='Escape')close();if(e.key==='Tab'){const items=[...modal.querySelectorAll('button,input,textarea,a[href]')],first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};window.addEventListener('keydown',handler);return()=>{document.body.style.overflow=overflow;window.removeEventListener('keydown',handler);before?.focus()}},[active]);}
export default function ShowcasePage({kind='expertise'}){
 const spaces=kind==='spaces',meta=spaces?spacesMeta:expertiseMeta;
 const [menu,setMenu]=useState(false),[enquiry,setEnquiry]=useState(null),[sent,setSent]=useState(false),[selected,setSelected]=useState(null);const trigger=useRef(null);
 const open=value=>{trigger.current=document.activeElement;setSent(false);setEnquiry(value);setMenu(false)};
 useEffect(()=>{document.title=meta.title;const el=document.querySelector('meta[name="description"]');if(el)el.content=meta.description},[meta]);
 useDialog(enquiry||selected,()=>{setEnquiry(null);setSelected(null)},trigger);
 return <div className="showcase-page"><a className="about-skip-link" href="#showcase-content">Skip to content</a><main inert={enquiry||selected?true:undefined}><SiteHeader menu={menu} setMenu={setMenu} open={open} about current={kind}/><div id="showcase-content" tabIndex={-1}>
 <section className="showcase-intro"><p className="eyebrow"><i/> BHB BUSINESS HUB / {spaces?'OUR SPACES':'OUR EXPERTISE'}</p><h1>{spaces?'Space for your':'People behind your'}<br/><em>{spaces?'next chapter.':'next chapter.'}</em></h1><div className="showcase-intro-bottom"><p>{spaces?'A closer look at the places where business happens. Explore our actual offices, meeting room and reception in Dubai.':'Business begins with a conversation. Meet the people ready to discuss your workspace and business needs.'}</p><a href={spaces?'#spaces-gallery':'#team'}>{spaces?'Explore our spaces':'Meet the team'} <ArrowRight size={18}/></a></div></section>
 {spaces?<section className="spaces-gallery" id="spaces-gallery" aria-label="Our office spaces">{rooms.map((room,i)=><article className={'space-card '+(i===0?'space-feature':'')} key={room.id}><button className="space-photo" onClick={()=>{trigger.current=document.activeElement;setSelected(room)}} aria-label={`View full photograph: ${room.type}`}><Photo id={room.id} alt={room.alt} eager={i===0}/><span className="photo-expand"><Plus size={18}/> View space</span></button><div className="space-caption"><div><p className="eyebrow">0{i+1} / {room.type.toUpperCase()}</p><h2>{room.name}</h2></div><ArrowUpRight size={24} strokeWidth={1}/></div></article>)}</section>:<><section className="team-section" id="team" aria-labelledby="team-title"><div className="team-intro"><p className="eyebrow">01 / THE BHB TEAM</p><h2 id="team-title">A personal<br/><em>connection.</em></h2><p>Connect with our team to discuss your plans and the next step for your business.</p><button className="outline-button" onClick={()=>open('General enquiry')}>Talk to our team <ArrowUpRight size={18}/></button></div><div className="team-grid">{team.map(person=><article className="team-card" key={person.id}><div className="team-photo"><Photo id={person.id} alt={`${person.name}, ${person.role} at BHB Business Hub`} portrait eager/></div><div className="team-caption"><h3>{person.name}</h3><p>{person.role}</p></div></article>)}</div></section><section className="expertise-support" aria-labelledby="support-title"><p className="eyebrow">02 / AREAS OF SUPPORT</p><h2 id="support-title">Your needs.<em> Connected.</em></h2><div className="support-grid">{support.map(([enquiry,title,text],i)=><button key={title} onClick={()=>open(enquiry)}><span>0{i+1}</span><h3>{title}</h3><p>{text}</p><ArrowUpRight size={22}/></button>)}</div></section></>}
 <section className="showcase-cta"><p className="eyebrow">LET’S START A CONVERSATION</p><h2>{spaces?'Find your place at BHB.':'Make your next move.'}</h2><p>{spaces?'Tell us how you work. Let’s discuss a space that fits.':'Tell us what you have in mind.'}</p><button className="gold-button" onClick={()=>open(spaces?'Flexible offices':'General enquiry')}>{spaces?'Discuss your office needs':'Contact our team'} <ArrowUpRight size={19}/></button><a href={spaces?'/expertise/':'/spaces/'}>{spaces?'Meet our team':'Explore our spaces'} <ArrowRight size={16}/></a></section></div><SiteFooter/></main>
 {enquiry&&<EnquiryDialog enquiry={enquiry} sent={sent} onClose={()=>setEnquiry(null)} onSent={()=>setSent(true)}/>}{selected&&<div className="photo-modal-backdrop" onClick={()=>setSelected(null)}><div className="photo-modal" role="dialog" aria-modal="true" aria-labelledby="photo-title" onClick={e=>e.stopPropagation()}><button className="photo-close" onClick={()=>setSelected(null)} aria-label="Close photograph"><X/></button><img src={`/photos/${selected.id}-1440.webp`} alt={selected.alt}/><h2 id="photo-title">{selected.type}</h2><p>{selected.name}</p></div></div>}</div>
}
export function SpacesPage(){return <ShowcasePage kind="spaces"/>}
